my_type=hypothesis
proj=hdfs
u_test=org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
h_list[1]=dfs.namenode.replication.max-streams@@@hdfs:NameNode@@@1@@@2@@@3
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
h_list: dfs.namenode.replication.max-streams@@@hdfs:NameNode@@@1@@@2@@@3
updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v1v2 running time = 14295751405
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
h_list: dfs.namenode.replication.max-streams@@@hdfs:NameNode@@@1@@@2@@@3
vv_mode: v1v2
result: FAIL
failureMessage: expected:<2> but was:<3>
stackTrace: java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling.testHeartbeat(TestHeartbeatHandling.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v1v1 running time = 14564029746
updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v2v2 running time = 14635099784
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v1v2 running time = 15585708961
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
h_list: dfs.namenode.replication.max-streams@@@hdfs:NameNode@@@1@@@2@@@3
vv_mode: v1v2
result: FAIL
failureMessage: expected:<2> but was:<3>
stackTrace: java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling.testHeartbeat(TestHeartbeatHandling.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v1v1 running time = 13901831593
updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v2v2 running time = 12923897108
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v1v2 running time = 14142654912
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
h_list: dfs.namenode.replication.max-streams@@@hdfs:NameNode@@@1@@@2@@@3
vv_mode: v1v2
result: FAIL
failureMessage: expected:<2> but was:<3>
stackTrace: java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling.testHeartbeat(TestHeartbeatHandling.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v1v1 running time = 15545511102
updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v2v2 running time = 14699928184
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v1v2 running time = 15384960516
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
h_list: dfs.namenode.replication.max-streams@@@hdfs:NameNode@@@1@@@2@@@3
vv_mode: v1v2
result: FAIL
failureMessage: expected:<2> but was:<3>
stackTrace: java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling.testHeartbeat(TestHeartbeatHandling.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v1v1 running time = 13852942473
updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v2v2 running time = 14139285462
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v1v2 running time = 11768300758
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
h_list: dfs.namenode.replication.max-streams@@@hdfs:NameNode@@@1@@@2@@@3
vv_mode: v1v2
result: FAIL
failureMessage: expected:<2> but was:<3>
stackTrace: java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling.testHeartbeat(TestHeartbeatHandling.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v1v1 running time = 12818980789
updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v2v2 running time = 14645931332
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v1v2 running time = 14471544624
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
h_list: dfs.namenode.replication.max-streams@@@hdfs:NameNode@@@1@@@2@@@3
vv_mode: v1v2
result: FAIL
failureMessage: expected:<2> but was:<3>
stackTrace: java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling.testHeartbeat(TestHeartbeatHandling.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v1v1 running time = 13867928325
updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v2v2 running time = 14883512602
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v1v2 running time = 14907191092
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
h_list: dfs.namenode.replication.max-streams@@@hdfs:NameNode@@@1@@@2@@@3
vv_mode: v1v2
result: FAIL
failureMessage: expected:<2> but was:<3>
stackTrace: java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling.testHeartbeat(TestHeartbeatHandling.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v1v1 running time = 16896695052
updating test result for file org.apache.hadoop.hdfs.server.blockmanagement.TestHeartbeatHandling#testHeartbeat
v2v2 running time = 16557253985
---> v1v1 and v2v2 test test suceeded.
early stop after 7 is satisfied
v1v2 failed with probability 7 out of 7
v1v1v2v2 failed with probability 0 out of 7
Total execution time in seconds : 304
0
