my_type=hypothesis
proj=hdfs
u_test=org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list[1]=dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@60s
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@60s
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 21643845326
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@60s
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 17478694107
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 18071945258
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 19794351288
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@60s
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 16873950575
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 19864201436
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 21537262616
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@60s
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 17414733775
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 18272655223
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 19645127329
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@60s
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 16677407771
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 19257633780
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 19935522169
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@60s
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 16532790614
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 17828595063
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 18835749110
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@60s
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 16929700871
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 17982361568
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 19669181666
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@60s
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 15551085427
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 17134061505
---> v1v1 and v2v2 test test suceeded.
early stop after 7 is satisfied
v1v2 failed with probability 7 out of 7
v1v1v2v2 failed with probability 0 out of 7
Total execution time in seconds : 386
0
