my_type=hypothesis
proj=hdfs
u_test=org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list[1]=dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@60s@@@0
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@60s@@@0
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 20846484063
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@60s@@@0
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 16947139636
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 15840262835
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 19851673839
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@60s@@@0
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 18023539567
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 16556245764
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 19342639509
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@60s@@@0
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 16664414620
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 15343873728
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 21901279844
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@60s@@@0
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 20124280967
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 16438675650
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 22522126534
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@60s@@@0
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 18836287029
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 17590099542
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 20214183294
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@60s@@@0
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 17058607165
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 16542806328
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 20062071045
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@60s@@@0
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 17729942214
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 16472238849
---> v1v1 and v2v2 test test suceeded.
early stop after 7 is satisfied
v1v2 failed with probability 7 out of 7
v1v1v2v2 failed with probability 0 out of 7
Total execution time in seconds : 384
0
